apiVersion: v1
description: I'm too lazy to write a description
name: cncf-demo
version: 0.0.1
dependencies:
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: db.enabled.helm