apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dot-production
  region: us-east-1
  version: "1.29"
managedNodeGroups:
  - name: primary
    instanceType: t3.large
    minSize: 1
    maxSize: 3
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
