apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: dot
  region: us-east-1
  version: "1.25"
managedNodeGroups:
  - name: primary
    instanceType: t3.medium
    minSize: 3
    maxSize: 6
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
